
services:
  mqtt-broker:
    build:
      context: ./mqtt-broker
      dockerfile: Dockerfile.mqttbroker
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9090:9090"  # expose metrics
    restart: unless-stopped

  # mqtt-broker2:
  #   build:
  #     context: ./mqtt-broker
  #     dockerfile: Dockerfile.mqttbroker
  #   container_name: mqtt-broker2
  #   ports:
  #     - "1884:1883"
  #     - "9095:9090"  # expose metrics
  #   restart: unless-stopped  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus                            # Config
      - /Volumes/MinhazStorage/docker-file-shared/prometheus_data:/prometheus  # Data
    ports:
      - "9091:9090"  # Prometheus web UI
    depends_on:
      - mqtt-broker

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /Volumes/MinhazStorage/docker-file-shared/grafana_data:/var/lib/grafana  # Dashboards & settings
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    restart: unless-stopped
