version: '3.8'

services:
  mqtt-broker:
    build:
      context: ./mqtt-broker
      dockerfile: Dockerfile.mqttbroker
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9090:9090"  # expose metrics
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9091:9090"  # Prometheus web UI
    depends_on:
      - mqtt-broker

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
