version: '3.8'

services:
  mqtt-broker:
    build:
      context: ./mqtt-broker
      dockerfile: Dockerfile.mqttbroker
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    restart: unless-stopped
