services:
  nextjs:
    build:
      context: ./login-auth-app
      dockerfile: Dockerfile.nextjs
    container_name: next-auth-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/authdb
      - JWT_SECRET=super_secure_key
    working_dir: /app
    command: npm run dev
    networks:
      - shared-net

  websocket-relay:
    build:
      context: ./login-auth-app
      dockerfile: Dockerfile.server
    container_name: websocket-relay
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    working_dir: /app
    depends_on:
      - nextjs
    networks:
      - shared-net

networks:
  shared-net:
    external: true
