services:
  nextjs:
    build:
      context: ./login-auth-app
      dockerfile: Dockerfile.nextjs
    container_name: next-auth-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/authdb
      - JWT_SECRET=super_secure_key
    working_dir: /app
    command: npm run dev
    networks:
      - shared-net

  websocket-connection:
    build:
      context: ./db-websocket
      dockerfile: Dockerfile.websocket  # or Dockerfile.ws if you named it differently
    container_name: websocket-connection
    ports:
      - "8080:8080"
    networks:
      - shared-net


networks:
  shared-net:
    external: true
