FROM node:18

WORKDIR /app

# Copy only package files first
COPY package.json package-lock.json* ./

# Install fresh deps inside container
RUN npm install

# Now copy the actual source code
COPY . .

EXPOSE 3000

# CMD ["npm", "run", "dev"]
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
