services:
  nextjs:
    build:
      context: ./login-auth-app
      dockerfile: Dockerfile.nextjs
    container_name: next-auth-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@serverside_db:5432/authdb
      - JWT_SECRET=super_secure_key
    depends_on:
      - serverside_db
    volumes:
      - ./login-auth-app:/app:cached
      - /app/node_modules  # prevent overwriting container-built node_modules
    working_dir: /app
    command: npm run dev

  serverside_db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
